### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by DooZolz** [mythicrp/mythic_phone#1]
Is there any chance you would be able to make a V2 of "mythic_inventory" to release? I know this isn't an issue but idk where else to ask you know, I saw the vid u made for "mythic_interiors" and I really like ur inventory style and would love to have it! I understand if you want to keep it private for now though

**Comment by Alzar** [comment]
Probably not, likely won't be releasing anything further in any official FiveM release as I just cannot be bothered to maintain a version that will work outside of my framework.

And no real interest in making source for my inventory public as it'd just be spammed with requests to get it to work for ESX/VRP and ... well hard pass on that. Nothing I've done is overly complex and can easily be replicated
